TYPO3:
  Neos:
    userInterface:
      requireJsPathMapping:
        'Flownative.NeosSortableEditor': 'resource://Flownative.NeosSortableEditor/Public/JavaScript'
      inspector:
        editors:
          'Flownative.NeosSortableEditor/SortableAssetEditor':
            editorOptions:
              fileChooserLabel: 'TYPO3.Neos:Main:choose'
